version: "3.3"

volumes:
  mongodb:
  data:

networks:
  default:
    external:
      name: fritz_net

services:

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: dmitryduev/kowalski_api:latest
    volumes:
      - data:/data
    expose:
      - "4000"
    # fixme:
    ports:
      - "4000:4000"
    links:
      - mongo:kowalski-mongo
    restart: always
    depends_on:
      - mongo

  ingester:
    build:
      context: .
      dockerfile: ingester.Dockerfile
    image: dmitryduev/kowalski_ingester:latest
    volumes:
      - data:/data
    links:
      - mongo:kowalski-mongo
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    # fixme:
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadminsecret
    volumes:
      - mongodb:/data/db
    restart: always
    # run as a replica set of size 1
    command: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
